-- ---------------------------------------------------------------------------
-- | Driver for the MoreSTLC interpreter.
--
-- Pipeline:   source text
--               -> LexMoreSTLC.myLexer      (generated by BNFC/Alex)
--               -> ParMoreSTLC.pTerm        (generated by BNFC/Happy)
--               -> TypeCheck.typeOf         (*** you write this ***)
--               -> Eval.eval                (*** you write this ***)
--               -> PrintMoreSTLC.printTree  (generated by BNFC)
--
-- A source file holds exactly one term, because in MoreStlc.v a term is the
-- whole structure of a program.  Several files may be given at once, and each
-- is handled independently:
--
--     morestlc examples/04-factorial.mstlc
--     morestlc examples/*.mstlc
--
-- Nothing here needs to be changed by students.
-- ---------------------------------------------------------------------------
module Main (main) where

import Prelude
import Control.Exception (SomeException, evaluate, try)
import System.Environment (getArgs, getProgName)
import System.Exit (exitFailure, exitSuccess)
import System.IO (hPutStrLn, stderr)

import AbsMoreSTLC
import ParMoreSTLC (myLexer, pTerm)

import qualified Env
import Eval (eval, renderRuntimeError)
import Pretty (ppTerm, ppType)
import TypeCheck (renderTypeError, typeOf)

-- ---------------------------------------------------------------------------
-- Command line
-- ---------------------------------------------------------------------------

data Mode
  = Run          -- ^ parse, type check, evaluate  (default)
  | TypeOnly     -- ^ parse and type check
  | ParseOnly    -- ^ parse only
  | ShowAst      -- ^ dump the abstract syntax tree
  | ShowPretty   -- ^ pretty print the term back out
  | RoundTrip    -- ^ parse, print, parse again, compare the two trees
  deriving (Eq, Show)

usage :: String -> String
usage prog = unlines
  [ "usage: " ++ prog ++ " [OPTION] [FILE...]"
  , ""
  , "Reads one MoreSTLC term from each FILE (or from stdin when no FILE is"
  , "given), type checks it and evaluates it."
  , ""
  , "  --run          parse, type check and evaluate            (default)"
  , "  --type-only    parse and type check, do not evaluate"
  , "  --parse-only   parse only"
  , "  --ast          print the abstract syntax tree"
  , "  --print        pretty print the term"
  , "  --roundtrip    parse, pretty print, parse again and compare the trees"
  , "  -h, --help     this message"
  ]

parseArgs :: [String] -> Either String (Mode, [FilePath])
parseArgs = go Run []
  where
    go mode files [] = Right (mode, reverse files)
    go mode files (a : as) = case a of
      "--run"        -> go Run        files as
      "--type-only"  -> go TypeOnly   files as
      "--parse-only" -> go ParseOnly  files as
      "--ast"        -> go ShowAst    files as
      "--print"      -> go ShowPretty files as
      "--roundtrip"  -> go RoundTrip  files as
      _ | take 1 a == "-" -> Left ("unknown option: " ++ a)
        | otherwise       -> go mode (a : files) as

main :: IO ()
main = do
  prog <- getProgName
  args <- getArgs
  if any (`elem` ["-h", "--help"]) args
    then putStr (usage prog) >> exitSuccess
    else case parseArgs args of
      Left msg -> do
        hPutStrLn stderr (prog ++ ": " ++ msg)
        hPutStrLn stderr (usage prog)
        exitFailure
      Right (mode, files) -> do
        oks <- case files of
          [] -> do
            src <- getContents
            r <- runOne mode False "<stdin>" src
            return [r]
          _ -> mapM (\f -> readFile f >>= runOne mode (length files > 1) f) files
        if and oks then exitSuccess else exitFailure

-- ---------------------------------------------------------------------------
-- One term
-- ---------------------------------------------------------------------------

-- | @runOne mode showName name src@ handles the single term in @src@.  When
--   several files were given, @showName@ is set and each line of output is
--   prefixed with the file it came from.
runOne :: Mode -> Bool -> String -> String -> IO Bool
runOne mode showName name src =
  case pTerm (myLexer src) of
    Left err -> do
      hPutStrLn stderr (name ++ ": parse error: " ++ err)
      return False
    Right t -> case mode of
      ParseOnly  -> emit (prefix ++ "parsed OK") >> return True
      ShowAst    -> emit (prefix ++ show t) >> return True
      ShowPretty -> emit (prefix ++ ppTerm t) >> return True
      RoundTrip  -> roundTrip name t
      TypeOnly   -> guarded name (check False t)
      Run        -> guarded name (check True t)
  where
    prefix = if showName then name ++ ": " else ""

    check :: Bool -> Term -> IO Bool
    check doEval t = case typeOf Env.empty t of
      Left terr -> do
        hPutStrLn stderr (name ++ ": type error: " ++ renderTypeError terr)
        return False
      Right ty
        | not doEval -> emit (prefix ++ ppType ty) >> return True
        | otherwise -> case eval t of
            Left rerr -> do
              hPutStrLn stderr (name ++ ": runtime error: " ++ renderRuntimeError rerr)
              return False
            Right v -> emit (prefix ++ ppTerm v ++ " : " ++ ppType ty) >> return True

-- | The pretty printer is derived from the same grammar as the parser, so
--   printing a tree and parsing the result must give the tree back.  This is
--   the sanity check for the front end itself.
roundTrip :: String -> Term -> IO Bool
roundTrip name t =
  case pTerm (myLexer (ppTerm t)) of
    Left err -> do
      hPutStrLn stderr (name ++ ": roundtrip FAILED, reprinted text does not parse: " ++ err)
      return False
    Right reparsed
      | reparsed == t -> do
          putStrLn (name ++ ": roundtrip OK")
          return True
      | otherwise -> do
          hPutStrLn stderr (name ++ ": roundtrip FAILED, trees differ")
          hPutStrLn stderr ("  original: " ++ show t)
          hPutStrLn stderr ("  reparsed: " ++ show reparsed)
          return False

-- | Force the line before printing it, so that a stub that calls 'error'
--   cannot leave a half written line behind.
emit :: String -> IO ()
emit s = do
  _ <- evaluate (length s)
  putStrLn s

-- | Turn an exception raised by an unimplemented stub into a normal failure
--   rather than a crash, so that the remaining files are still processed.
guarded :: String -> IO Bool -> IO Bool
guarded name act = do
  r <- try act
  case r of
    Right b -> return b
    Left e -> do
      hPutStrLn stderr (name ++ ": " ++ show (e :: SomeException))
      return False
